services:
  # --- Service Base de Données ---
  db:
    image: postgres:16-alpine
    container_name: gamer-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # --- Service Backend ---
  api:
    build: ./server
    container_name: gamer-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - DB_DIALECT=postgres
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      - db

  # --- Service Frontend (Client) ---
  client:
    build: ./client
    container_name: gamer-client
    ports:
      - "8080:80" # Port du site
    depends_on:
      - api

volumes:
  db_data:
